# Generated by Django 3.1.7 on 2021-05-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('synopsis', models.CharField(default='', max_length=500)),
                ('num_clues', models.IntegerField()),
                ('user', models.CharField(default='', max_length=100)),
            ],
            options={
                'unique_together': {('title', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_id', models.IntegerField()),
                ('clue_num', models.IntegerField()),
                ('clue_text', models.CharField(default='', max_length=1000)),
                ('clue_img_url', models.TextField(default='')),
                ('parent_list', models.TextField(default='[]')),
                ('story', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conf.story')),
            ],
            options={
                'unique_together': {('story', 'clue_id')},
            },
        ),
    ]
